setair = false
setmeowdelenie = true
blocksupdate = false
setblockontick = 200
smartrotateon = true
language = "rus"

[meownatics]
source4 = "fly.mbp"
source1 = "save_meownatic_2.mbp"
source2 = "save_meownatic_1.mbp"
source3 = "meownatic_schem.mbp"
