setair = false
setmeowdelenie = true
language = "rus"
setentities = false
smartrotateon = true
setblockontick = 200
entitiessave = true
blocksupdate = false

[meownatics]
source1 = "save_meownatic_5.mbp"
