smartrotateon = true
blocksupdate = false
setair = false
setblockontick = 200
language = "rus"
copyair = false
setmeowdelenie = true
[meownatics]
source4 = "CityMeownatic.arbd"
source2 = "Broken_Sphere.arbd"
source1 = "police_station.arbd"
source3 = "blu_spaceship.arbd"

