blocksupdate = false
smartrotateon = true
setblockontick = 200
copyair = false
setmeowdelenie = true
setair = true
[meownatics]
source1 = "police_station.arbd"
source3 = "save_meownatic_1.arbd"
source2 = "Broken_Sphere.arbd"

